version: "3.7"
services:
  node:
    build: ./docker/node
    container_name: replica-yt-node
    ports:
      - "1234:1234"
      - "8080:8080"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
